version: '3.8'
services:
  web-crawler:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
    command: ["conda", "run", "--no-capture-output", "-n", "web-crawler", "python", "web-crawler.py"]